### ISSUE TITLE
Reset outline property

### ISSUE THREAD

**Issue by nakp** [nathansmith/960-Grid-System#8]
I've noticed that in reset.css there's no outline reset and chrome adds an outline for input fields that should be overriden with

``` css
*:focus {outline: none;}
```
